features: 
  - { feature:bgp }
  - { feature: pim }
  - { feature: ospf }

ospf_process_id: UNDERLAY

ospf_area: 0
asn: 65022
address_families:
  - { afi: l2vpn, safi: evpn }
  - { afi: ipv4, safi: unicast }

bgp_neighbors:
  - { remote_as: 65006, neighbor: 6.6.6.6, update_source: Loopback0 }
  - { remote_as: 65005, neighbor: 5.5.5.5, update_source: Loopback0 }

router_id: 22.22.22.22 